/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.ac.bg.fon.ai.ProjekatKosarka.view.igraci;

import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import rs.ac.bg.fon.ai.ProjekatKosarka.controller.UIController;
import rs.ac.bg.fon.ai.ProjekatKosarka.domain.Igraci;
import rs.ac.bg.fon.ai.ProjekatKosarka.domain.Pozicija;
import rs.ac.bg.fon.ai.ProjekatKosarka.model_tabele.TabelaIgraciModelTabele;

/**
 *
 * @author Korisnik
 */
@Component
@Scope("prototype")
public class IgraciPretraziFrame extends javax.swing.JDialog implements ItemListener{

    @Autowired
    private ApplicationContext applicationContext;
    /**
     * Creates new form IgraciPretraziFrame
     */
    
   

    
    
    private PromeniIgracaFrame promeniIgracaFrame;
    final Frame parent;
    final TabelaIgraciModelTabele modelTabele;
    final UIController controller;
    
    @Autowired
    private Igraci igrac;
    

    public IgraciPretraziFrame(java.awt.Frame parent, boolean modal, TabelaIgraciModelTabele modelTabele, UIController controller) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
        this.modelTabele = modelTabele;
        this.controller = controller;
        checkIzmeni.setSelected(true);
        prepareForm();
        
    }

    private void prepareForm() {
        checkIzmeni.addItemListener(this);
        checkObrisi.addItemListener(this);
        modelTabele.getListaIgraci().clear();
        tblIgraci.setModel(modelTabele);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtVisina = new javax.swing.JTextField();
        txtBroj1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIgraci = new javax.swing.JTable();
        btnFiltriraj = new javax.swing.JButton();
        cmbPozicija = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        checkObrisi = new javax.swing.JCheckBox();
        checkIzmeni = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Broj");

        jLabel4.setText("Visina");

        jLabel5.setText("Pozicija");

        tblIgraci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIgraci);

        btnFiltriraj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFiltriraj.setText("Pronadji igrace");
        btnFiltriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrirajActionPerformed(evt);
            }
        });

        cmbPozicija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PG", "SG", "SF", "PF", "C" }));

        jButton1.setText("Ucitaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkObrisi.setText("obrisi");

        checkIzmeni.setText("izmeni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBroj1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(txtPrezime)
                    .addComponent(txtIme)
                    .addComponent(txtVisina)
                    .addComponent(cmbPozicija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkObrisi)
                        .addGap(34, 34, 34)
                        .addComponent(checkIzmeni))
                    .addComponent(btnFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBroj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVisina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkObrisi)
                    .addComponent(checkIzmeni))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrirajActionPerformed
        try {
            String ime = null;
            String prezime = null;
            Double visina = null;
            Integer broj = null;
            Pozicija pozicija = null;
            if (!txtIme.getText().isBlank()) {
                ime = txtIme.getText();
            }
            if (!txtPrezime.getText().isBlank()) {
                prezime = txtPrezime.getText();
            }
            if (!txtVisina.getText().isBlank()) {
                visina = Double.valueOf(txtVisina.getText());
            }
            if (!txtBroj1.getText().isBlank()) {
                broj = Integer.valueOf(txtBroj1.getText());
            }

         
            pozicija = Pozicija.valueOf(String.valueOf(cmbPozicija.getSelectedItem()));
              igrac.setBroj(broj);
            igrac.setPozicija(pozicija);
            igrac.setIme(ime);
            igrac.setPrezime(prezime);
            igrac.setVisina(visina);
            List<Igraci> mojiIgraci = controller.vratiSveIgraceFiltrirane(igrac);
            if(mojiIgraci!=null){
                    modelTabele.setListaIgraci(mojiIgraci);
                    modelTabele.fireTableDataChanged();
            
            }else{
                JOptionPane.showMessageDialog(this, "Nije pronadjen nijedan igrac sa zadatim filterom");
            }
        

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnFiltrirajActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tblIgraci.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita clana","Obavestenje",JOptionPane.WARNING_MESSAGE);
            dispose();
            return;
        }
        
        igrac = modelTabele.getListaIgraci().get(tblIgraci.getSelectedRow());
        promeniIgracaFrame = applicationContext.getBean(PromeniIgracaFrame.class);
        if(checkObrisi.isSelected())
             promeniIgracaFrame.setMode(true);
        if(checkIzmeni.isSelected())
            promeniIgracaFrame.setMode(false);
        promeniIgracaFrame.setIgrac(igrac);
        
        modelTabele.fireTableDataChanged();
        promeniIgracaFrame.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltriraj;
    private javax.swing.JCheckBox checkIzmeni;
    private javax.swing.JCheckBox checkObrisi;
    private javax.swing.JComboBox<String> cmbPozicija;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIgraci;
    private javax.swing.JTextField txtBroj1;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtVisina;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
         if (e.getSource() == checkObrisi) {
            // If checkbox1 is checked, disable checkbox2
            if (checkObrisi.isSelected()) {
                checkIzmeni.setSelected(false);
            } 
        } else if (e.getSource() == checkIzmeni) {
            // If checkbox2 is checked, disable checkbox1
            if (checkIzmeni.isSelected()) {
                checkObrisi.setSelected(false);
            } 
        }
    }
}
